### PR TITLE
Association - private events: Feature/butaca events

### PR DESCRIPTION
**Pull request by diazgio**
### Private Events

in this project we:
- Created Association Web app.
- Add Linters.
- Add Gems from Ruby like Bundle, bootstrap,  Hirb.
- Add an association between the events and the user models through the attendance model (many to many).
- Add basic OOP.

### CODE REVIEW

**Review by javitocor — CHANGES_REQUESTED** [review]
# STATUS CHANGES REQUIRED 🛑 

Good job so far with this project! 👍 
Your code is clean and readable! 💯 
Good job with the styling! 👏 
However, we need to implement some changes to get the project approved 💪 
Kindly check my comments below 👇  and resubmit our project for a new code review once they are done ⏩ 
Good luck! 😺 
## Mandatory changes
- Modify your readme file since Devise and simple form are not gems in this project
- Events controller index action:
* [ ] lists past events, i.e. `@past_events = Event.previous_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists ucomping events, i.e. `@upcoming_events = Event.upcoming_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- User controller show action:
* [ ] lists events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- The tests are not working, kindly change the, you can use RSpec and capybara

**Comment by diazgio** [comment]
Hi thanks for the review, I'm changing the readme, and also if You can see the Upcoming events and Past events are displaying on the Event's Show page and also on the User's Show page, here some screenshots as examples:
User's show page: 
usershowpage

show page:
showpage2

showpage1

**Review by BrittanyBlake — CHANGES_REQUESTED** [review]
### Status: Changes Required ♻️ 
****
### Hi Team! 👋 
You have done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] You do not currently have any tests. This was pointed out to you by the previous TSE and it is a requirement.  See screenshots from the odin project for information on what tests are needed 👇 
Screen Shot 2020-10-29 at 10 26 51 PM
Screen Shot 2020-10-29 at 10 27 11 PM
Screen Shot 2020-10-29 at 10 27 25 PM


****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Comment by javitocor** [comment]
> Hi thanks for the review, I'm changing the readme, and also if You can see the Upcoming events and Past events are displaying on the Event's Show page and also on the User's Show page, here some screenshots as examples:
> User's show page:
> usershowpage
> 
> show page:
> showpage2
> 
> showpage1

Hello team! 
Your app is working fine, and the design is amazing! Good job with it and keep it up! 
I can see the past and future events on your show pages, but you must implement them from the controller and not with logic in the views, it is a better practice, cleaner code and easier to debug. It is also a requirement for the project!

Best regards!
Any doubts you can contact me on slack!

**Review by lekegitrepo — APPROVED** [review]
## Status: Approved :heavy_check_mark:
#### Hi @diazgio :clap: :clap:
#### You have done an incredible job :star: by implementing the required changes. This project is approved :white_check_mark:

#### _Reviewed by Temitayo Adeleke_

**Pull request merged**
